### HTTP variables
@BASE_URL= http://localhost:3333

### Create Transaction
POST {{BASE_URL}}/transactions HTTP/1.1
Content-Type: application/json

{
  "title": "Compras",
  "amount": 1500,
  "type": "debit"
}

### List all transactions
GET {{BASE_URL}}/transactions
Content-Type: application/json

### List transaction by id
GET {{BASE_URL}}/transactions/87324dee-47f4-4bff-a9b2-df3688bb74e4
Content-Type: application/json

### Get transaction summary
GET {{BASE_URL}}/transactions/summary
Content-Type: application/json